# Use the official Bun image
FROM oven/bun:latest AS base
WORKDIR /app

# Environment variables needed at build time
ARG AUTH0_CLIENT_ID
ARG AUTH0_DOMAIN
ARG AUTH0_CLIENT_SECRET
ARG AUTH0_CALLBACK_URL
ARG AUTH0_SECRET
ARG APP_BASE_URL
ARG NEXT_PUBLIC_FORUM_URL
ARG NEXT_DIRECTUS_STATIC_TOKEN

# Set environment variables for build time
ENV AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
ENV AUTH0_DOMAIN=${AUTH0_DOMAIN}
ENV AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
ENV AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
ENV AUTH0_SECRET=${AUTH0_SECRET}
ENV APP_BASE_URL=${APP_BASE_URL}
ENV NEXT_PUBLIC_FORUM_URL=${NEXT_PUBLIC_FORUM_URL}
ENV NEXT_DIRECTUS_STATIC_TOKEN=${NEXT_DIRECTUS_STATIC_TOKEN}
ENV NEXT_TELEMETRY_DISABLED=1

# Install dependencies
COPY package.json bun.lockb ./
RUN bun install

# Copy source code
COPY . .

# Set environment variables
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Build the application
RUN bun run build

# Start the application
CMD ["bun", "start"]

# Expose the port the app runs on
EXPOSE 3000
